# Generated by Django 2.2.7 on 2019-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191125_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='username',
            field=models.CharField(default='username', max_length=255),
            preserve_default=False,
        ),
    ]
