# Generated by Django 2.2.7 on 2019-11-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191125_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='credit',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
