# Generated by Django 2.2.7 on 2019-11-25 13:32

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191125_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceincrease',
            name='time_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='mcci_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
