# Generated by Django 2.2.7 on 2019-11-26 13:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191125_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceincrease',
            name='time_jalali',
        ),
        migrations.AlterField(
            model_name='balanceincrease',
            name='timestamp',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='timestamp',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
